### ISSUE TITLE
Dedication heading/title

### ISSUE THREAD

**Issue by drgrigg** [b-t-k/ben-jonson_the-alchemist#2]
Should "To the Reader" in dedication-to-reader be a heading? At present it's just an ordinary paragraph.

If so, the `<title>` contents should read the same as the heading.

**Comment by drgrigg** [comment]
On looking at local.css, I'm not sure why there is CSS to style the first paragraph like a heading, instead of making it a heading? I'm confused!

**Comment by b-t-k** [comment]
I discussed the heading in the original dedication and it was decided to leave the "heading" as body. So I just applied the same styling to the dedication to the reader. I got the styling from of examples in the corpus.

**Comment by drgrigg** [comment]
OK, I understand. But I still think the `<title>` tag should read "To the Reader" to match the pseudo-heading on the page.

**Comment by b-t-k** [comment]
Can do...Done.
