### ISSUE TITLE
Non-semantic italics

### ISSUE THREAD

**Issue by drgrigg** [b-t-k/ben-jonson_the-alchemist#3]
There seem to be a number of italicised phrases in Act 4 which don't have any semantic information, but seem (on a quick glance) to be Italian, eg:

`<i>En gallanta madama, Don! Gallantissima!</i>`

Apologies if you've discussed this with Alex already.

**Comment by b-t-k** [comment]
These are gibberish mocking of Spanish. It didn't see right o mark them as "es"
